version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - NODE_ENV=development
    command: npm run dev
    tty: true
    stdin_open: true
